# Generated by Django 2.1.4 on 2019-04-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='split_bill',
            fields=[
                ('sbill_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.IntegerField()),
                ('split', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='split_bill',
            name='suser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.users'),
        ),
        migrations.AddField(
            model_name='group',
            name='gbill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.split_bill'),
        ),
        migrations.AddField(
            model_name='group',
            name='gusers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='euser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.users'),
        ),
        migrations.AddField(
            model_name='buddy',
            name='buser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.users'),
        ),
    ]
